from typing import Any, Iterable, Tuple

class Compose:
    def __init__(self, transforms: Iterable[Any]) -> None: ...
    def __call__(self, img: Any) -> Any: ...

class Resize:
    def __init__(self, size: Tuple[int, int]) -> None: ...
    def __call__(self, img: Any) -> Any: ...

class ToTensor:
    def __call__(self, img: Any) -> Any: ...

class Normalize:
    def __init__(self, mean: Tuple[float, float, float], std: Tuple[float, float, float]) -> None: ...
    def __call__(self, tensor: Any) -> Any: ...
