from typing import Any, Tuple, List
import numpy as np

COLOR_BGR2HSV: int
COLOR_BGR2RGB: int
RETR_EXTERNAL: int
CHAIN_APPROX_SIMPLE: int

def cvtColor(src: np.ndarray, code: int) -> np.ndarray: ...
def inRange(src: np.ndarray, lowerb: np.ndarray, upperb: np.ndarray) -> np.ndarray: ...
def findContours(image: np.ndarray, mode: int, method: int) -> Tuple[List[np.ndarray], Any]: ...
def drawContours(image: np.ndarray, contours: List[np.ndarray], contourIdx: int, color: Tuple[int, int, int], thickness: int) -> Any: ...
def bitwise_and(src1: np.ndarray, src2: np.ndarray, mask: np.ndarray | None = ...) -> np.ndarray: ...
def imwrite(filename: str, img: np.ndarray) -> bool: ...
def countNonZero(src: np.ndarray) -> int: ...
