from typing import Any, Tuple
import numpy as np

class _Params:
    debug: Any

params: _Params

def gaussian_blur(*, img: np.ndarray, ksize: Tuple[int, int], sigma_x: int) -> np.ndarray: ...
def fill(mask: np.ndarray, size: int) -> np.ndarray: ...
def erode(mask: np.ndarray, ksize: int, i: int) -> np.ndarray: ...
def dilate(mask: np.ndarray, ksize: int, i: int) -> np.ndarray: ...

class roi:
    @staticmethod
    def rectangle(*, img: np.ndarray, x: int, y: int, h: int, w: int) -> np.ndarray: ...
    @staticmethod
    def filter(*, mask: np.ndarray, roi: np.ndarray, roi_type: str) -> np.ndarray: ...

class analyze:
    @staticmethod
    def size(*, img: np.ndarray, labeled_mask: np.ndarray, n_labels: int, label: str) -> np.ndarray: ...
    @staticmethod
    def color(*, rgb_img: np.ndarray, mask: np.ndarray, colorspaces: str, label: str) -> Any: ...

class morphology:
    @staticmethod
    def check_cycles(*, mask: np.ndarray) -> Any: ...

def readimage(path: str) -> Tuple[np.ndarray, Any, Any]: ...
